server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  datasource:
    url: jdbc:mysql://localhost:3306/meetnow?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password:  # ?? ??? ?
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true # sql ??? ??
        default_batch_fetch_size: 1000

    show-sql: true  # sql ??
    open-in-view: false

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9:
  eyJzdWIiOiJBQ0NFU1MiLCJhdWQiOiLso7zrj5nshJ0iLCJpYXQiOjE2NzM1MjIyNjgsImV4cCI6MTY3OTUyMjI2OH0:
    NXSnkoEH25Zbrt08ZiWjS9XtHBm3KE_ERamKMOHLgmA9O968i0Y4Tf92gtvwPU_EQoE6TiHTZFW99NbWzO30Mg:
logging:
  level:
    org.hibernate.type: trace

jwt:
  secret:

